# Generated by Django 3.2.3 on 2021-09-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_no', models.IntegerField(max_length=7)),
                ('lottery_price', models.IntegerField(max_length=8)),
            ],
        ),
    ]
