# Generated by Django 3.2.3 on 2021-09-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='lottery_no',
            field=models.CharField(max_length=7),
        ),
    ]
